name: Distribute

on:
  push:
    branches:
      - master
    paths-ignore:
      - README.md
      - .gitignore
      - .github/**
      - build/index.js
      - build/index.js.map
      - package-lock.json
      - package.json

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - run: npm install
#      - run: npm run test

      - name: Setup GIT
        run: |
          git reset --hard
          git config --local --list
          git checkout master
          git config user.email "tech@santeacademie.com"
          git config user.name "tagadabot"

      - name: Bump version
        run: |
          git reset --hard
          npm version patch
          npm run build
          git add . || true
          git commit -m "Build update" || true
          git push "https://$GITHUB_ACTOR:$GITHUB_TOKEN@github.com/$GITHUB_REPOSITORY"
        env:
          GITHUB_TOKEN: ${{secrets.TAGADABOT_READ_TOKEN}}

      - name: Update develop
        run: |
          git checkout develop
          git pull || true
          git reset --hard
          git pull || true
          git merge master
          git commit -m "Merge master into develop" || true
          git push "https://$GITHUB_ACTOR:$GITHUB_TOKEN@github.com/$GITHUB_REPOSITORY"
        env:
          GITHUB_TOKEN: ${{secrets.TAGADABOT_READ_TOKEN}}

      - name: Deploy remotely
        run: |
          curl https://bigbrowser.santeacademie.com/update.php
